//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblQuizChoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblQuizChoice()
        {
            this.tblTestAnswers = new HashSet<tblTestAnswer>();
        }
    
        public int Quiz_Choice_Id { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<bool> IsAnswer { get; set; }
        public string OptionTitle { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tblQuizQuestion tblQuizQuestion { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTestAnswer> tblTestAnswers { get; set; }
    }
}
