//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTestAnswer
    {
        public int TestAnswerId { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> QuizChoiceId { get; set; }
        public Nullable<bool> IsCorrectChoice { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
    
        public virtual tblQuizChoice tblQuizChoice { get; set; }
        public virtual tblTest tblTest { get; set; }
    }
}
