//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTest()
        {
            this.tblTestAnswers = new HashSet<tblTestAnswer>();
        }
    
        public int TestId { get; set; }
        public Nullable<int> QuizId { get; set; }
        public Nullable<int> Test_StatusId { get; set; }
        public Nullable<int> Score { get; set; }
        public Nullable<System.DateTime> CreatedON { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedON { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
    
        public virtual tblQuiz tblQuiz { get; set; }
        public virtual tblTestStatu tblTestStatu { get; set; }
        public virtual tblUser tblUser { get; set; }
        public virtual tblUser tblUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTestAnswer> tblTestAnswers { get; set; }
    }
}
